paths:
  /swagger:
    get:
      responses:
        200:
          description: Success
          schema:
            type: object

  /endpoints:
    get:
      responses:
        200:
          description: Success
          schema:
            type: object
